global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
